name: Deploy to Cloud Run (OIDC)

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: >-
            projects/1089127134552/locations/global/workloadIdentityPools/gh-pool/providers/gh-provider
          service_account: deploy-sa@sapient-duality-464111-n8.iam.gserviceaccount.com

      - name: Setup gcloud
        uses: google-github-actions/setup-gcloud@v2

      - name: Build & push container
        run: |
          gcloud builds submit \
            --project="${{ secrets.PROJECT_ID }}" \
            --tag "gcr.io/${{ secrets.PROJECT_ID }}/line-keiba-bot:latest"

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy line-keiba-bot \
            --image "gcr.io/${{ secrets.PROJECT_ID }}/line-keiba-bot:latest" \
            --platform=managed \
            --region=asia-northeast1 \
            --allow-unauthenticated \
            --set-env-vars "LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }},LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }}"
