name: OCR-Screenshot-Ingest
on:
  push:
    paths: ['Screenshot*.jpg']

jobs:
  ocr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}

      - run: pip install pillow pytesseract pandas

      - run: python scripts/ocr_batch.py --pattern "Screenshot*.jpg"

      - uses: actions/upload-artifact@v4
        with: {name: ocr_csv, path: output/ocr.csv}

      - run: curl -F "csv=@output/ocr.csv" "$WEBHOOK_URL"
        env: {WEBHOOK_URL: ${{ secrets.MODEL_WEBHOOK }}}
