name: OCR-Screenshot-Ingest

on:
  push:
    paths:
      - 'Screenshot*.jpg'

jobs:
  ocr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install system deps
        run: |
          sudo apt-get -qq update
          sudo apt-get -qq install -y tesseract-ocr tesseract-ocr-jpn

      - name: Install Python deps
        run: |
          pip install pillow pytesseract pandas

      - name: Run OCR
        run: |
          python scripts/ocr_batch.py --pattern "Screenshot*.jpg"

      - name: Upload CSV
        uses: actions/upload-artifact@v4
        with:
          name: ocr_csv
          path: output/ocr.csv

      - name: Call model webhook
        env:
          WEBHOOK_URL: ${{ secrets.MODEL_WEBHOOK }}
        run: |
          curl -F "csv=@output/ocr.csv" "$WEBHOOK_URL"
